<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Meu Site Simples</title>
</head>
<body>
    <header>
        <h1>Bem-vindo ao Meu Site!</h1>
    </header>
    <main>
        <p>Este é um parágrafo de introdução.</p>
        <img src="sua-imagem.jpg" alt="Descrição da imagem">
    </main>
    <footer>
        <p>&copy; 2024 Meu Site</p>
    </footer>
</body>
</html>
